[GitHub Actions] Flatpak: Migrate to new flat-manager-client

diff --git a/.github/workflows/CI_flatpak.yml b/.github/workflows/CI_flatpak.yml
--- a/.github/workflows/CI_flatpak.yml
+++ b/.github/workflows/CI_flatpak.yml
@@ -465,7 +465,7 @@ jobs:
           dnf update -y
           echo "::endgroup::"
           echo "::group::dnf install dependencies"
-          dnf install -y cmake git git-lfs dbus-daemon flatpak flatpak-builder python3-aiohttp python3-tenacity python3-gobject ccache zstd curl appstream
+          dnf install -y cmake git git-lfs dbus-daemon flatpak flatpak-builder python3-aiohttp python3-tenacity python3-gobject ccache zstd curl appstream ostree-libs
           echo "::endgroup::"
 
           echo "::group::flatpak remote-add"
@@ -474,8 +474,12 @@ jobs:
           flatpak remote-add --if-not-exists gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo
           echo "::endgroup::"
 
+          FLAT_MANAGER_CLIENT_URL="https://github.com/flatpak/flat-manager/releases/download/0.5.0/flat-manager-client.amd64"
+          FLAT_MANAGER_CLIENT_SHA256="9733a148ac185bc8d7fb0429a43f9ad7d934635760bb71933658642c697f87c9"
+
           echo "::group::fetch flat-manager-client"
-          curl -Lf https://raw.githubusercontent.com/flatpak/flat-manager/master/flat-manager-client --output /usr/bin/flat-manager-client
+          curl -Lf $FLAT_MANAGER_CLIENT_URL --output /usr/bin/flat-manager-client
+          echo "$FLAT_MANAGER_CLIENT_SHA256  /usr/bin/flat-manager-client" | sha256sum -c - || { echo "Error: Hash mismatch for flat-manager-client"; exit 1; }
           chmod +x /usr/bin/flat-manager-client
           echo "::endgroup::"
       - uses: actions/checkout@v6
