[GitHub Actions] Windows: Build new combined (universal) Windows installer

diff --git a/.github/workflows/CI_windows.yml b/.github/workflows/CI_windows.yml
--- a/.github/workflows/CI_windows.yml
+++ b/.github/workflows/CI_windows.yml
@@ -597,48 +597,6 @@ jobs:
         echo "::add-matcher::${{ github.workspace }}\src\.ci\githubactions\pattern_matchers\clang.json"
         & cmake --build . --config Release --target warzone2100 -- -k0
         echo "::remove-matcher owner=clang::"
-    - name: Package Portable Installer
-      working-directory: '${{ github.workspace }}\build'
-      env:
-        FULL_CMAKE_PATH: '${{ steps.settings.outputs.WZ_FULL_CMAKE_PATH }}'
-      run: |
-        . "${env:WZ_REPO_PATH}\.ci\powershell\importVCvars.ps1"
-        Import-VCVarsEnv "${env:WZ_VISUAL_STUDIO_INSTALL_PATH}" "-arch=${env:WZ_TARGET_ARCH} -host_arch=x64"
-        # Run CPack
-        & "${env:FULL_CMAKE_PATH}\cpack.exe" -D CPACK_PACKAGE_FILE_NAME="warzone2100_portable" -D CPACK_WZ_PORTABLE=ON -G NSIS -C "Release"
-        # Rename the portable installer
-        Move-Item -LiteralPath ".\warzone2100_portable.exe" -Destination "${{ github.workspace }}\output\portable\warzone2100_$($env:WZ_BUILD_DESC)_portable.exe"
-    - name: Collect Failure Logs
-      if: failure()
-      run: |
-        $NSIS_Log = "build\_CPack_Packages\win32\NSIS\NSISOutput.log"
-        if (Test-Path $NSIS_Log -PathType Leaf)
-        {
-          Copy-Item -LiteralPath "$NSIS_Log" -Destination ".\logs\error_logs"
-        }
-        $NSIS_Log = "build\_CPack_Packages\win64\NSIS\NSISOutput.log"
-        if (Test-Path $NSIS_Log -PathType Leaf)
-        {
-          Copy-Item -LiteralPath "$NSIS_Log" -Destination ".\logs\error_logs"
-        }
-    - name: Upload Failure Logs Artifact
-      uses: actions/upload-artifact@v4
-      if: failure()
-      with:
-        name: failure_${{ steps.settings.outputs.WZ_BUILD_DESC }}_${{ matrix.architecture }}_error_logs
-        path: '${{ github.workspace }}\logs\error_logs'
-        if-no-files-found: 'warn'
-    - name: Package Full Installer
-      working-directory: '${{ github.workspace }}\build'
-      env:
-        FULL_CMAKE_PATH: '${{ steps.settings.outputs.WZ_FULL_CMAKE_PATH }}'
-      run: |
-        . "${env:WZ_REPO_PATH}\.ci\powershell\importVCvars.ps1"
-        Import-VCVarsEnv "${env:WZ_VISUAL_STUDIO_INSTALL_PATH}" "-arch=${env:WZ_TARGET_ARCH} -host_arch=x64"
-        # Run CPack
-        & "${env:FULL_CMAKE_PATH}\cpack.exe" -D CPACK_PACKAGE_FILE_NAME="warzone2100_installer" -D CPACK_WZ_PORTABLE=OFF -G NSIS -C "Release"
-        # Rename the archive
-        Move-Item -LiteralPath ".\warzone2100_installer.exe" -Destination "${{ github.workspace }}\output\installer\warzone2100_$($env:WZ_BUILD_DESC)_installer.exe"
     - name: Archive .ZIP of Regular build
       working-directory: '${{ github.workspace }}\build'
       env:
@@ -664,29 +622,13 @@ jobs:
     - name: Compare Build Outputs
       working-directory: '${{ github.workspace }}\output'
       run: |
-        # Log hashes of the setup EXEs
+        # Log hashes of the build output
         Write-Host "SHA512 Hashes:"
-        Write-Host "`nwarzone2100_$($env:WZ_BUILD_DESC)_portable.exe`n`t-> SHA512: $((Get-FileHash -LiteralPath ".\portable\warzone2100_$($env:WZ_BUILD_DESC)_portable.exe" -Algorithm SHA512).Hash)`n`t`-> Size (bytes): $((Get-Item -LiteralPath ".\portable\warzone2100_$($env:WZ_BUILD_DESC)_portable.exe").Length)"
-        Write-Host "`nwarzone2100_$($env:WZ_BUILD_DESC)_installer.exe`n`t-> SHA512: $((Get-FileHash -LiteralPath ".\installer\warzone2100_$($env:WZ_BUILD_DESC)_installer.exe" -Algorithm SHA512).Hash)`n`t`-> Size (bytes): $((Get-Item -LiteralPath ".\installer\warzone2100_$($env:WZ_BUILD_DESC)_installer.exe").Length)"
         Write-Host "`nwarzone2100_$($env:WZ_BUILD_DESC)_archive.zip`n`t-> SHA512: $((Get-FileHash -LiteralPath ".\archive\warzone2100_$($env:WZ_BUILD_DESC)_archive.zip" -Algorithm SHA512).Hash)`n`t`-> Size (bytes): $((Get-Item -LiteralPath ".\archive\warzone2100_$($env:WZ_BUILD_DESC)_archive.zip").Length)"
         Write-Host ""
     #####################################################
     # Upload build artifacts
     #####################################################
-    - name: 'Upload Artifact - (Portable Build)'
-      uses: actions/upload-artifact@v4
-      if: success() && (github.repository == 'Warzone2100/warzone2100')
-      with:
-        name: warzone2100_${{ steps.settings.outputs.WZ_BUILD_DESC }}_portable
-        path: '${{ github.workspace }}\output\portable'
-        if-no-files-found: 'error'
-    - name: 'Upload Artifact - (Regular Installer)'
-      uses: actions/upload-artifact@v4
-      if: success() && (github.repository == 'Warzone2100/warzone2100')
-      with:
-        name: warzone2100_${{ steps.settings.outputs.WZ_BUILD_DESC }}_installer
-        path: '${{ github.workspace }}\output\installer'
-        if-no-files-found: 'error'
     - name: 'Upload Artifact - (Debug Symbols)'
       uses: actions/upload-artifact@v4
       if: success() && (github.repository == 'Warzone2100/warzone2100')
@@ -696,7 +638,7 @@ jobs:
         if-no-files-found: 'error'
     - name: 'Upload Artifact - (Archive)'
       uses: actions/upload-artifact@v4
-      if: success() && ((github.event_name == 'push' && github.ref == 'refs/heads/master') || (github.event_name == 'workflow_run' && github.event.workflow_run.name == 'Draft Tag Release')) && (matrix.deploy_release == true) && (github.repository == 'Warzone2100/warzone2100')
+      if: success() && (matrix.deploy_release == true)
       with:
         name: warzone2100_${{ steps.settings.outputs.WZ_BUILD_DESC }}_archive
         path: '${{ github.workspace }}\output\archive'
@@ -704,20 +646,6 @@ jobs:
     #####################################################
     # Generate artifact attestations
     #####################################################
-    - name: 'Generate artifact attestation - (Portable Build)'
-      # Run on push to master branch (development build), or tag release automation build
-      if: success() && ((github.event_name == 'push' && github.ref == 'refs/heads/master') || (github.event_name == 'workflow_run' && github.event.workflow_run.name == 'Draft Tag Release'))
-      uses: actions/attest-build-provenance@v2
-      continue-on-error: true
-      with:
-        subject-path: '${{ github.workspace }}\output\portable\*'
-    - name: 'Generate artifact attestation - (Regular Installer)'
-      # Run on push to master branch (development build), or tag release automation build
-      if: success() && ((github.event_name == 'push' && github.ref == 'refs/heads/master') || (github.event_name == 'workflow_run' && github.event.workflow_run.name == 'Draft Tag Release'))
-      uses: actions/attest-build-provenance@v2
-      continue-on-error: true
-      with:
-        subject-path: '${{ github.workspace }}\output\installer\*'
     - name: 'Generate artifact attestation - (Archive)'
       # Run on push to master branch (development build), or tag release automation build
       if: success() && ((github.event_name == 'push' && github.ref == 'refs/heads/master') || (github.event_name == 'workflow_run' && github.event.workflow_run.name == 'Draft Tag Release'))
@@ -771,6 +699,148 @@ jobs:
         path: '${{ github.workspace }}\sentry_output\sentry_source_bundles'
         retention-days: 1
         if-no-files-found: 'warn'
+  combined-installer-build:
+    name: 'Build Installer'
+    permissions:
+      contents: read
+      # needed to generate artifact attestations, see: https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds
+      id-token: write
+      attestations: write
+    runs-on: windows-latest
+    needs: windows-build
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          path: 'src'
+      - name: Configure Repo Checkout
+        id: checkout-config
+        working-directory: '${{ github.workspace }}\src'
+        shell: bash
+        env:
+          WORKFLOW_RUN_CONCLUSION: ${{ github.event.workflow_run.conclusion }}
+          WORKFLOW_RUN_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
+        run: |
+          . .ci/githubactions/checkout_config.sh
+      - name: Prepare Git Repo for autorevision
+        working-directory: '${{ github.workspace }}\src'
+        run: cmake -P .ci/githubactions/prepare_git_repo.cmake
+      - name: Init Git Submodules
+        working-directory: '${{ github.workspace }}\src'
+        run: |
+          # To save time, only init the submodules in the pkg/win_installer/ folder
+          git submodule update --init --recursive -- pkg/win_installer/innohelperscripts pkg/win_installer/resources
+      - name: Prep Environment
+        id: settings
+        shell: bash
+        run: |
+          mkdir dependency-dl
+          mkdir innosetup
+          mkdir innosetup-deps
+          mkdir built-archives
+          mkdir tmp
+          mkdir combined-staging
+          mkdir output
+      - name: Install Inno Setup
+        env:
+          INNOSETUP_INSTALL_PATH: '${{ github.workspace }}\innosetup'
+        run: |
+          Start-Sleep -Milliseconds 1 # See: https://stackoverflow.com/a/49859001
+          $VerbosePreference = "Continue"
+          . "src\.ci\powershell\request.ps1"
+
+          $INNOSETUP_DL_URL = "https://files.jrsoftware.org/is/6/innosetup-6.4.3.exe"
+          $INNOSETUP_DL_SHA256 = "f3c42116542c4cc57263c5ba6c4feabfc49fe771f2f98a79d2f7628b8762723b"
+
+          $INNOSETUP_DL_PATH = ".\dependency-dl\innosetup.exe"
+          $req = Req -Params @{ 'Method'='GET';'Uri'="$INNOSETUP_DL_URL";'OutFile'="${INNOSETUP_DL_PATH}" } -Retries 3 -SecondsDelay 10 -ExpectedHash "${INNOSETUP_DL_SHA256}" -Algorithm SHA256
+
+          # Install portably (to avoid conflict with any version that's shipped in the GitHub Actions images)
+          Write-Host "Installing Inno Setup..."
+          Start-Process -FilePath "${INNOSETUP_DL_PATH}" -ArgumentList /portable=1,"/DIR=${env:INNOSETUP_INSTALL_PATH}",/CURRENTUSER,/NOICONS,/VERYSILENT,/SUPPRESSMSGBOXES,/NORESTART -NoNewWindow -Wait
+          Write-Host "Finished installing Inno Setup"
+
+          echo "WZ_INNOSETUP_PATH=${env:INNOSETUP_INSTALL_PATH}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
+          echo "WZ_INNOSETUP_PATH=${env:INNOSETUP_INSTALL_PATH}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
+      - name: Install Install Script Dependencies
+        id: script-dependencies
+        env:
+          SCRIPT_DEP_INSTALL_PATH: '${{ github.workspace }}\innosetup-deps'
+        run: |
+          Start-Sleep -Milliseconds 1 # See: https://stackoverflow.com/a/49859001
+          $VerbosePreference = "Continue"
+          . "src\.ci\powershell\request.ps1"
+
+          $FILECHECK_DL_URL = "https://github.com/past-due/innofilecheck/releases/download/v1.0.1/innofilecheck.dll"
+          $FILECHECK_DL_SHA512 = "a2983b025c56c8c134427360dcc1b07a55b14b9e4700ea7ccdb99d0a23537adb41e1d19f116b7358747def2c2f27c773fdc3f8bb4faf3acb516d2f8b288de194"
+
+          $FILECHECK_DL_PATH = ".\dependency-dl\innofilecheck.dll"
+          $req = Req -Params @{ 'Method'='GET';'Uri'="$FILECHECK_DL_URL";'OutFile'="${FILECHECK_DL_PATH}" } -Retries 3 -SecondsDelay 10 -ExpectedHash "${FILECHECK_DL_SHA512}" -Algorithm SHA512
+
+          $installLocation = "$(Join-Path "${env:SCRIPT_DEP_INSTALL_PATH}" "innofilecheck.dll")"
+          Move-Item -Path "${FILECHECK_DL_PATH}" -Destination "$installLocation" -Force -ErrorAction Stop
+
+          echo "WZ_INNOSETUP_SCRIPT_DEPENDENCIES_PATH=${env:SCRIPT_DEP_INSTALL_PATH}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
+      - name: Download Architecture Archives
+        uses: actions/download-artifact@v4
+        with:
+          pattern: 'warzone2100_win_*_archive'
+          path: .\built-archives
+          merge-multiple: true
+      - name: Log Archive Details
+        working-directory: '${{ github.workspace }}\built-archives'
+        run: |
+          Write-Host "SHA512 Hashes:"
+          $files = Get-ChildItem -Path . -File
+          foreach ($file in $files) {
+            Write-Host "`n$($file.Name)`n`t-> SHA512: $((Get-FileHash -Path "$file" -Algorithm SHA512).Hash)`n`t`-> Size (bytes): $((Get-Item -Path "$file").Length)"
+          }
+          Write-Host ""
+      - name: Create Combined Staging of Arch Builds
+        env:
+          BASE_WORKING_PATH: '${{ github.workspace }}'
+        run: |
+          $VerbosePreference = "Continue"
+          $InformationPreference = "Continue"
+          . "src\pkg\win_combined_archive\build_win_combined_arch.ps1"
+          Build-WinCombinedArchDir -InputArchivesDir "${env:BASE_WORKING_PATH}\built-archives" -TmpExtractDir "${env:BASE_WORKING_PATH}\tmp" -BuildDir "${env:BASE_WORKING_PATH}\combined-staging"
+          Get-ChildItem -Path "${env:BASE_WORKING_PATH}\combined-staging" -Recurse -File
+      - name: Build Combined Installer
+        id: build-installer
+        env:
+          INSTALLER_SOURCE_DIR: '${{ github.workspace }}\combined-staging'
+          INSTALLER_OUTPUT_DIR: '${{ github.workspace }}\output'
+          INNOFILECHECK_DLL_DIR: '${{ steps.script-dependencies.outputs.WZ_INNOSETUP_SCRIPT_DEPENDENCIES_PATH }}'
+        run: |
+          & "${env:WZ_INNOSETUP_PATH}\ISCC.exe" "/O${env:INSTALLER_OUTPUT_DIR}" "/DSOURCE_DIR=${env:INSTALLER_SOURCE_DIR}" "/DINNOFILECHECK_DLL_DIR=${env:INNOFILECHECK_DLL_DIR}" "src\pkg\win_installer\warzone2100.iss"
+          if ($? -eq $false) {
+            Write-Error "Failed building installer"
+            Exit 1
+          }
+          $OutputFile = "$(Join-Path "${env:INSTALLER_OUTPUT_DIR}" "warzone2100_win_installer.exe")"
+          Write-Host "Finished building installer:"
+          Write-Host "`n$($OutputFile)`n`t-> SHA512: $((Get-FileHash -Path "$OutputFile" -Algorithm SHA512).Hash)`n`t`-> Size (bytes): $((Get-Item -Path "$OutputFile").Length)"
+          echo "INSTALLER_OUTPUT_DIR=${env:INSTALLER_OUTPUT_DIR}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
+          echo "INSTALLER_EXE=${OutputFile}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
+      - name: Debug Output - Install Manifest
+        env:
+          INSTALLER_OUTPUT_DIR: '${{ steps.build-installer.outputs.INSTALLER_OUTPUT_DIR }}'
+        run: |
+          Get-Content "${env:INSTALLER_OUTPUT_DIR}\setup-manifest.txt"
+      - name: 'Upload Artifact - (Combined Installer)'
+        uses: actions/upload-artifact@v4
+        if: success() && (github.repository == 'Warzone2100/warzone2100')
+        with:
+          name: warzone2100_win_installer
+          path: ${{ steps.build-installer.outputs.INSTALLER_EXE }}
+          if-no-files-found: 'error'
+      - name: 'Generate Artifact Attestation'
+        # Run on push to master branch (development build), or tag release automation build
+        if: success() && ((github.event_name == 'push' && github.ref == 'refs/heads/master') || (github.event_name == 'workflow_run' && github.event.workflow_run.name == 'Draft Tag Release'))
+        uses: actions/attest-build-provenance@v2
+        continue-on-error: true
+        with:
+          subject-path: '${{ steps.build-installer.outputs.INSTALLER_EXE }}'
   upload-release-assets:
     name: 'Upload Release Assets'
     permissions:
@@ -778,7 +848,7 @@ jobs:
     runs-on: ubuntu-latest
     # Run on tag release automation build
     if: success() && (github.event_name == 'workflow_run' && github.event.workflow_run.name == 'Draft Tag Release') && (github.repository == 'Warzone2100/warzone2100')
-    needs: windows-build
+    needs: [windows-build, combined-installer-build]
     env:
       WZ_GITHUB_REF: ${{needs.windows-build.outputs.WZ_GITHUB_REF}}
     steps:
@@ -789,7 +859,7 @@ jobs:
       - name: Download Release Artifacts
         uses: actions/download-artifact@v4
         with:
-          # Includes the release artifacts: portable installer, full installer, debug symbols, and archive
+          # Includes the release artifacts: installer, debug symbols, and archive
           pattern: 'warzone2100_win_*'
           path: ./upload-assets
           merge-multiple: true
