[GitHub Actions] Use FetchSentryCLI.cmake

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -123,6 +123,7 @@ jobs:
           CURRENT_TAG_COMMIT="$(git rev-list -n 1 "${GITHUB_REF}")"
           echo "CURRENT_TAG_COMMIT=${CURRENT_TAG_COMMIT}"
 
+          echo "WZ_REPO_PATH=$(pwd)" >> $GITHUB_ENV
           echo "SENTRY_VERSION=${SENTRY_VERSION}" >> $GITHUB_ENV
           echo "PRIOR_TAG_COMMIT=${PRIOR_TAG_COMMIT}" >> $GITHUB_ENV
           echo "CURRENT_TAG_COMMIT=${CURRENT_TAG_COMMIT}" >> $GITHUB_ENV
@@ -141,14 +142,18 @@ jobs:
             echo "No SENTRY_VERSION - skipping"
             exit 0
           fi
-          docker pull getsentry/sentry-cli
+          # Download sentry-cli
+          echo "::group::Downloading sentry-cli ..."
+          cmake -P "${WZ_REPO_PATH}/.ci/githubactions/FetchSentryCLI.cmake"
+          echo "Downloading sentry-cli ... Done"
+          echo "::endgroup::"
           # Check if release already exists
           echo "Checking if release exists: ${SENTRY_VERSION}"
-          if ! docker run --rm -e SENTRY_AUTH_TOKEN -e SENTRY_ORG -v "$(pwd):/work" getsentry/sentry-cli releases info "${SENTRY_VERSION}" -q; then
+          if ! ./sentry-cli/sentry-cli releases info "${SENTRY_VERSION}" -q; then
             # Create the release
             echo "Creating the release: ${SENTRY_VERSION}"
-            docker run --rm -e SENTRY_AUTH_TOKEN -e SENTRY_ORG -v "$(pwd):/work" getsentry/sentry-cli releases new -p warzone2100 "${SENTRY_VERSION}" || echo "Failed to create the release?"
+            ./sentry-cli/sentry-cli releases new -p warzone2100 "${SENTRY_VERSION}" || echo "Failed to create the release?"
           fi
           # Associate commits with the release
           echo "Associate commits with the release: ${SENTRY_VERSION}"
-          docker run --rm -e SENTRY_AUTH_TOKEN -e SENTRY_ORG -v "$(pwd):/work" getsentry/sentry-cli releases set-commits "${SENTRY_VERSION}" --commit "Warzone2100/warzone2100@${PRIOR_TAG_COMMIT}..${CURRENT_TAG_COMMIT}"
+          ./sentry-cli/sentry-cli releases set-commits "${SENTRY_VERSION}" --commit "Warzone2100/warzone2100@${PRIOR_TAG_COMMIT}..${CURRENT_TAG_COMMIT}"
